name: Variable Test

on:
  workflow_dispatch:
    inputs:
      variableValue:
        description: 'Enter stage or dev'
        default: 'stage'
        required: true

env:
  stage: 'www.arun.stage.com'
  dev: 'www.arun.dev.com'
  qa : 'www.arun.qa.com'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print URL based on input
        run: |
          if [ "${{ github.event.inputs.variableValue }}" = "stage" ]; then
            echo "URL: ${{ env.stage }}"
          elif [ "${{ github.event.inputs.variableValue }}" = "dev" ]; then
            echo "URL: ${{ env.dev }}"
          elseif [ "${{ github.event.inputs.variableValue }}" = "qa" ]; then echo "URL: ${{ env.qa }}"
          else
            echo "Invalid input: ${{ github.event.inputs.variableValue }}"
          fi
        env:
          qa: 'arun'
