name: Variable Test

on:
  workflow_dispatch:
    inputs:
      variableValue:
        description: 'Enter Variable'
        default: '1234'
        required: true
        type: string

env:
  firstVariable: 'first'
  secondVariable: 'second'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print variables
        run: |
          echo "First Variable: ${{ env.firstVariable }}"
          echo "Second Variable: ${{ env.secondVariable }}"
          echo "Input Variable: ${{ github.event.inputs.variableValue }}"
